spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/lock_test
    username: root
    password:

  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        highlight_sql: true
    hibernate:
      ddl-auto: create